version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
     - db
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'trangx'
      # You can use whatever password you like
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # Password for root access
      MYSQL_ROOT_PASSWORD: ''
      
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./initdb/init.sql:/var/lib/mysql/init.sql
    command: --init-file /var/lib/mysql/init.sql